name = "Minecraft Minecolloniesserver"
author = "Esel.com"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14df41a48e6bfbf8d7b6b85f021d31e02d1ba8a326cf910462f5aa5ec6223034"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"

[options]
no-internal-hashes = true
