name = "Minecraft Minecolloniesserver"
author = "Esel.com"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb538a9883ff46c5effe36d9d0e6fa93d16d157b314c7ef3fc0c5a9680f59a3c"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
neoforge = "47.1.105"
